function  t_pl = Plot_LLE_Dressed_State(CW,ind)

    Dressed_State   = CW.An.Omega_mu;
    Dressed_State_1 = Dressed_State(1,:);%max(Dressed_State,[],2);
    Dressed_State_2 = Dressed_State(2,:);%min(Dressed_State,[],2);
    
%%

%     t_pl = proPlot(fftshift(L_L.CW.Space.k),fftshift(Pure_State)/2/pi/1E6,[],'Marker','o','FaceAlpha',0.5);
%     t_pl = t_pl.addData(fftshift(L_L.CW.Space.k),fftshift(Pure_State)/2/pi/1E6, ones(1,N_mode)*L_L.CW.In.kappa/2/2/pi/1E6,...
%                     'PlotType', 'errorbar', ...
%                     'Color', [238, 102, 119]/255,...
%                     'LineStyle', 'none',...
%                     'UIStack','bottom');
    t_pl = proPlot(fftshift(CW.Space.k),fftshift(Dressed_State_1)/2/pi/1E6,[],'Marker','o');
    t_pl = t_pl.addData(fftshift(CW.Space.k),fftshift(Dressed_State_1)/2/pi/1E6, ones(1,CW.Space.N)*CW.In.kappa/2/2/pi/1E6,...
                    'PlotType', 'errorbar', ...
                    'Color', [238, 102, 119]/255,...
                    'LineStyle', 'none',...
                    'UIStack','bottom');
    t_pl = t_pl.addData(fftshift(CW.Space.k),fftshift(Dressed_State_2)/2/pi/1E6,[],'Marker','o');
    t_pl = t_pl.addData(fftshift(CW.Space.k),fftshift(Dressed_State_2)/2/pi/1E6, ones(1,CW.Space.N)*CW.In.kappa/2/2/pi/1E6,...
                    'PlotType', 'errorbar', ...
                    'Color', [238, 102, 119]/255,...
                    'LineStyle', 'none',...
                    'UIStack','bottom');
%%
    t_pl = t_pl.changeAxisOptions('XLabelText','$\mu$',...
                         'YLabelText','$\omega_\mu (MHz)$',...  
                         'FontSize',13,'XLim',[-15,15] );
%%
    figure;
    t_pl.plotData
    
%%

end

